# Generated by Django 4.2.16 on 2024-12-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0012_rename_student_discuss_s_id_remove_reply_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='T_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.teacher'),
        ),
    ]
