# Generated by Django 4.2.16 on 2024-12-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0013_discuss_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='T_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.teacher'),
        ),
    ]
