# Generated by Django 4.2.16 on 2024-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0014_reply_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
