# Generated by Django 4.2.16 on 2024-12-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0015_student_email_student_phonenumber_teacher_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('K_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordDiscuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.discuss')),
                ('K_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.keyword')),
            ],
        ),
    ]
